// ══════════════════════════════════════════════════════════════
// Athenas — Ícones (biblioteca Phosphor Icons )
// Traço arredondado e amigável, no clima \"cute French adventure\".
// Usa currentColor → acompanha os temas automaticamente.
// ══════════════════════════════════════════════════════════════
import {
  Airplane,
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  Bed,
  Basket,
  Bird,
  BookOpen,
  Books,
  BowlFood,
  Brain,
  Briefcase,
  Bug,
  Butterfly,
  Cake,
  Calendar,
  Camera,
  Car,
  Cat,
  ChalkboardTeacher,
  ChatCircle,
  ChatCircleDots,
  ChartBar,
  ChatCircleText,
  Check,
  CheckCircle,
  City,
  Clock,
  CloudSun,
  Coffee,
  Compass,
  Confetti,
  Cow,
  Crosshair,
  Crown,
  CrownSimple,
  Desk,
  Dog,
  Drop,
  Ear,
  Fire,
  Fish,
  Flag,
  Flame,
  Flower,
  FlowerLotus,
  FlowerTulip,
  ForkKnife,
  Gear,
  GenderFemale,
  Gift,
  Globe,
  GraduationCap,
  HandHeart,
  HandWaving,
  Hash,
  Heart,
  HeartStraight,
  Heartbeat,
  Horse,
  Hourglass,
  House,
  Infinity,
  Info,
  Leaf,
  Lightbulb,
  Lightning,
  Lock,
  MagicWand,
  MagnifyingGlass,
  MapTrifold,
  MaskHappy,
  Medal,
  MedalMilitary,
  Microphone,
  Moon,
  MusicNote,
  NotePencil,
  Palette,
  PawPrint,
  PencilSimple,
  PhoneCall,
  Play,
  ShirtFolded,
  PlayCircle,
  Question,
  Rabbit,
  Radio,
  Robot,
  Rocket,
  Scales,
  SealCheck,
  ShieldCheck,
  Signpost,
  Smiley,
  SmileyMeh,
  SmileySad,
  SmileyXEyes,
  Sparkle,
  SpeakerHigh,
  Star,
  StarFour,
  Storefront,
  Student,
  StarHalf,
  Sun,
  SunDim,
  Sword,
  Target,
  Tornado,
  Train,
  Trash,
  Trophy,
  User,
  Users,
  TextAa,
  VideoCamera,
  Warning,
  Wrench,
  WifiHigh,
  X,
  XCircle,
  type Icon as PhosphorIcon
} from "@phosphor-icons/react";
import type { IconName } from "@/types";

const MAP: Record<IconName, PhosphorIcon> = {
  home: House,
  house: House,
  cloudSun: CloudSun,
  map: MapTrifold,
  brain: Brain,
  chat: ChatCircle,
  user: User,
  flame: Flame,
  star: Star,
  trophy: Trophy,
  book: BookOpen,
  mic: Microphone,
  speaker: SpeakerHigh,
  back: ArrowLeft,
  gear: Gear,
  lock: Lock,
  check: Check,
  shield: ShieldCheck,
  crown: Crown,
  sparkle: Sparkle,
  play: Play,
  x: X,
  heart: Heart,
  search: MagnifyingGlass,
  sword: Sword,
  compass: Compass,
  leaf: Leaf,
  bowlFood: BowlFood,
  city: City,
  airplane: Airplane,
  graduationCap: GraduationCap,
  briefcase: Briefcase,
  books: Books,
  maskHappy: MaskHappy,
  globe: Globe,
  fire: Fire,
  moon: Moon,
  handWaving: HandWaving,
  handHeart: HandHeart,
  checkCircle: CheckCircle,
  hash: Hash,
  palette: Palette,
  calendar: Calendar,
  scales: Scales,
  users: Users,
  forkKnife: ForkKnife,
  lightning: Lightning,
  clock: Clock,
  xCircle: XCircle,
  hourglass: Hourglass,
  signpost: Signpost,
  train: Train,
  rocket: Rocket,
  target: Target,
  starFour: StarFour,
  flower: Flower,
  flowerTulip: FlowerTulip,
  flowerLotus: FlowerLotus,
  drop: Drop,
  cake: Cake,
  sun: Sun,
  flag: Flag,
  medal: Medal,
  medalMilitary: MedalMilitary,
  crosshair: Crosshair,
  crownSimple: CrownSimple,
  robot: Robot,
  heartStraight: HeartStraight,
  arrowClockwise: ArrowClockwise,
  chatCircleDots: ChatCircleDots,
  chalkboardTeacher: ChalkboardTeacher,
  magicWand: MagicWand,
  lightbulb: Lightbulb,
  confetti: Confetti,
  bird: Bird,
  gift: Gift,
  trash: Trash,
  smileySad: SmileySad,
  playCircle: PlayCircle,
  ear: Ear,
  musicNote: MusicNote,
  radio: Radio,
  wifiHigh: WifiHigh,
  pawPrint: PawPrint,
  bug: Bug,
  butterfly: Butterfly,
  fish: Fish,
  dog: Dog,
  horse: Horse,
  cow: Cow,
  coffee: Coffee,
  rabbit: Rabbit,
  cat: Cat,
  question: Question,
  warning: Warning,
  info: Info,
  genderFemale: GenderFemale,
  bed: Bed,
  tornado: Tornado,
  videoCamera: VideoCamera,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  smiley: Smiley,
  smileyMeh: SmileyMeh,
  smileyXEyes: SmileyXEyes,
  heartbeat: Heartbeat,
  starHalf: StarHalf,
  sunDim: SunDim,
  chatText: ChatCircleText,
  infinity: Infinity,
  chartBar: ChartBar,
  sealCheck: SealCheck,
  textAa: TextAa,
  pencilSimple: PencilSimple,
  phoneCall: PhoneCall,
  shirtFolded: ShirtFolded,
  storefront: Storefront,
  basket: Basket,
  camera: Camera,
  car: Car,
  student: Student,
  desk: Desk,
  wrench: Wrench,
  notePencil: NotePencil
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number;
  filled?: boolean;
  strokeWidth?: number;
}

export function Icon({ name, size = 22, filled = false, ...rest }: IconProps) {
  const Cmp = MAP[name];
  if (!Cmp) return null;
  return <Cmp size={size} weight={filled ? "fill" : "regular"} aria-hidden {...rest} />;
}
